[workspace]

members = [
	"aas-server",
	"aas-protos",
]

exclude = [
	"examples/attestee-client",
]

[patch.crates-io]
grpcio-compiler = { rev = "a1549b6ac9675d01f472956f1aed54d463903b4b", git = "https://github.com/tikv/grpc-rs.git", version = "0.5", default-features = false }
