[workspace]

members = [
	"aas-server",
	"aas-protos",
]

exclude = [
	"examples/attestee-client",
]


[patch.crates-io]
grpcio-compiler = { git = "https://github.com/tikv/grpc-rs.git", version = "0.5", default-features = false }
