# This is for staging usage.
version: '3.4'
services:
  aas:
    build:
      context: .
      dockerfile: Dockerfile
    image: aas:latest
    ports:
      - 11800:11800
    volumes:
      - ./:/advanca:ro