[package]
name = "aas-protos"
version = "0.1.0"
authors = ["Chua Zheng Leong <czl@iiyume.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpcio   = { version = "0.4", features = ["openssl"] }
protobuf = { version = "~2" }
futures  = { version = "0.1" }

[build-dependencies]
protoc-grpcio = "1.1.0"
